export const queryKeys = {
  adminDashboard: ['admin', 'dashboard'] as const,
  customerDashboard: ['customer', 'dashboard'] as const,
  adminCustomers: ['admin', 'customers'] as const,
  adminCustomer: (customerId: string) => ['admin', 'customers', customerId] as const,
  adminCustomerPriceBook: (customerId: string) => ['admin', 'customers', customerId, 'priceBook'] as const,
  customerProfile: ['customer', 'profile'] as const,
  adminProducts: ['admin', 'products'] as const,
  customerProducts: ['customer', 'products'] as const,
  adminStandingOrders: ['admin', 'standingOrders'] as const,
  customerStandingOrder: ['customer', 'standingOrder'] as const,
  adminOrders: ['admin', 'orders'] as const,
  adminOrdersList: (params: unknown) => ['admin', 'orders', params] as const,
  customerOrders: ['customer', 'orders'] as const,
  adminInvoices: ['admin', 'invoices'] as const,
  adminInvoice: (invoiceId: string) => ['admin', 'invoices', invoiceId] as const,
  customerInvoices: ['customer', 'invoices'] as const,
  customerInvoice: (invoiceId: string) => ['customer', 'invoices', invoiceId] as const,
  adminStatements: ['admin', 'statements'] as const,
  adminStatement: (statementId: string) => ['admin', 'statements', statementId] as const,
  customerStatements: ['customer', 'statements'] as const,
  customerStatement: (statementId: string) => ['customer', 'statements', statementId] as const,
  production: ['admin', 'production'] as const,
  auditLogs: ['admin', 'logs', 'audit'] as const,
  auditLogsList: (params: unknown) => ['admin', 'logs', 'audit', params] as const,
  emailLogs: ['admin', 'logs', 'email'] as const,
  emailLogsList: (params: unknown) => ['admin', 'logs', 'email', params] as const,
};
