apiVersion: apps/v1
kind: Deployment
metadata:
  name: storycoffee-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: storycoffee-frontend
  template:
    metadata:
      labels:
        app: storycoffee-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: storycoffee-frontend
spec:
  selector:
    app: storycoffee-frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
