{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "storycoffee.secretName" . }}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ .Values.api.connectionString | quote }}
  Jwt__Secret: {{ .Values.api.jwtSecret | quote }}
  DocumentStorage__SigningSecret: {{ .Values.api.documentStorageSigningSecret | quote }}
  DocumentStorage__AccessKey: {{ .Values.api.documentStorageAccessKey | quote }}
  DocumentStorage__SecretKey: {{ .Values.api.documentStorageSecretKey | quote }}
  Email__SmtpUsername: {{ .Values.api.emailSmtpUsername | quote }}
  Email__SmtpPassword: {{ .Values.api.emailSmtpPassword | quote }}
  Email__WebhookSecret: {{ .Values.api.emailWebhookSecret | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
{{- end }}
